export interface Song {
  "Track": string,
  "Album Name": string,
  "Artist": string,
  "Release Date": "4/26/2024",
  "ISRC": string,
  "All Time Rank": number,
  "Track Score": number,
  "Spotify Streams": string,
  "Spotify Playlist Count": string,
  "Spotify Playlist Reach": string,
  "Spotify Popularity": number,
  "YouTube Views": string,
  "YouTube Likes": string,
  "TikTok Posts": string,
  "TikTok Likes": string,
  "TikTok Views": string,
  "YouTube Playlist Reach": string,
  "Apple Music Playlist Count": number,
  "AirPlay Spins": string,
  "SiriusXM Spins": number,
  "Deezer Playlist Count": number,
  "Deezer Playlist Reach": string,
  "Amazon Playlist Count": number,
  "Pandora Streams": string,
  "Pandora Track Stations": string,
  "Soundcloud Streams":string,
  "Shazam Counts":string,
  "TIDAL Popularity": string,
  "Explicit Track": 0 | 1
}