export interface Song {
  "Track": string,
  "Album Name": string,
  "Artist": string,
  "Release Date": string,
  "ISRC": string,
  "All Time Rank": number,
  "Track Score": number,
  "Spotify Streams": string | number,
  "Spotify Playlist Count": string | number,
  "Spotify Playlist Reach": string | number,
  "Spotify Popularity": string | number,
  "YouTube Views": string,
  "YouTube Likes": string,
  "TikTok Posts": string | number,
  "TikTok Likes": string,
  "TikTok Views": string,
  "YouTube Playlist Reach": string,
  "Apple Music Playlist Count": string | number,
  "AirPlay Spins": string | number,
  "SiriusXM Spins": string | number,
  "Deezer Playlist Count": string | number,
  "Deezer Playlist Reach": string | number,
  "Amazon Playlist Count": string | number,
  "Pandora Streams": string | number,
  "Pandora Track Stations": string | number,
  "Soundcloud Streams": string | number,
  "Shazam Counts":string,
  "TIDAL Popularity": string,
  "Explicit Track": number
}